import { Hero } from './heroesInterface';

export const HEROES: Hero[] = [
  {
    version: '6.24.1',
    id: 'Ekko',
    key: '245',
    name: 'Ekko',
    title: 'the Boy Who Shattered Time',
    blurb:
      'A prodigy from the rough streets of Zaun, Ekko manipulates time to spin any situation to his advantage. Using his own invention, the Zero-Drive, he explores the branching possibilities of reality. As well as experimenting with multi-dimensional ...',
    info: {
      attack: 5,
      defense: 3,
      magic: 7,
      difficulty: 8,
    },
    image: {
      full: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/bltf22ba7e6328e4376/5db05fbd242f426df132f963/RiotX_ChampionList_ekko.jpg?quality=90&width=250',
      sprite: 'champion0.png',
      group: 'champion',
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ['Assassin', 'Fighter'],
    partype: 'MP',
    stats: {
      hp: 580.0,
      hpperlevel: 80.0,
      mp: 280.0,
      mpperlevel: 50.0,
      movespeed: 340.0,
      armor: 27.0,
      armorperlevel: 3.0,
      spellblock: 32.0,
      spellblockperlevel: 1.25,
      attackrange: 125.0,
      hpregen: 9.0,
      hpregenperlevel: 0.9,
      mpregen: 7.0,
      mpregenperlevel: 0.8,
      crit: 0.0,
      critperlevel: 0.0,
      attackdamage: 55.0,
      attackdamageperlevel: 3.0,
      attackspeedoffset: 0.0,
      attackspeedperlevel: 3.3,
    },
  },
  {
    version: '6.24.1',
    id: 'Jinx',
    key: '222',
    name: 'Jinx',
    title: 'the Loose Cannon',
    blurb:
      'Jinx lives to wreak havoc without a thought for the consequences, leaving a trail of mayhem and panic in her wake. A manic and impulsive criminal, she despises nothing more than boredom, and gleefully brings her own volatile brand of pandemonium to ...',
    info: {
      attack: 9,
      defense: 2,
      magic: 4,
      difficulty: 6,
    },
    image: {
      full: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blta2cba784d9fad4b8/5db05fce89fb926b491ed817/RiotX_ChampionList_jinx.jpg?quality=90&width=250',
      sprite: 'champion1.png',
      group: 'champion',
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
    tags: ['Marksman'],
    partype: 'MP',
    stats: {
      hp: 517.76,
      hpperlevel: 82.0,
      mp: 245.6,
      mpperlevel: 45.0,
      movespeed: 325.0,
      armor: 22.88,
      armorperlevel: 3.5,
      spellblock: 30.0,
      spellblockperlevel: 0.0,
      attackrange: 525.0,
      hpregen: 5.84,
      hpregenperlevel: 0.5,
      mpregen: 6.68,
      mpregenperlevel: 1.0,
      crit: 0.0,
      critperlevel: 0.0,
      attackdamage: 58.46,
      attackdamageperlevel: 2.41,
      attackspeedoffset: 0.0,
      attackspeedperlevel: 1.0,
    },
  },
  {
    version: '6.24.1',
    id: 'Vi',
    key: '254',
    name: 'Vi',
    title: 'the Piltover Enforcer',
    blurb:
      "To Vi, every problem is just another brick wall to punch through with her gigantic hextech gauntlets. Though she grew up on the wrong side of the law, Vi now uses her criminal know-how to serve Piltover's police force. Vi's brash attitude, abrasive ...",
    info: {
      attack: 8,
      defense: 5,
      magic: 3,
      difficulty: 4,
    },
    image: {
      full: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt3bd79abf330fc807/5db06014dc674266df3d5d56/RiotX_ChampionList_vi.jpg?quality=90&width=250',
      sprite: 'champion3.png',
      group: 'champion',
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ['Fighter', 'Assassin'],
    partype: 'MP',
    stats: {
      hp: 582.8,
      hpperlevel: 85.0,
      mp: 295.6,
      mpperlevel: 45.0,
      movespeed: 345.0,
      armor: 25.88,
      armorperlevel: 3.5,
      spellblock: 32.1,
      spellblockperlevel: 1.25,
      attackrange: 125.0,
      hpregen: 9.01,
      hpregenperlevel: 0.9,
      mpregen: 8.09,
      mpregenperlevel: 0.65,
      crit: 0.0,
      critperlevel: 0.0,
      attackdamage: 55.88,
      attackdamageperlevel: 3.5,
      attackspeedoffset: -0.03,
      attackspeedperlevel: 2.5,
    },
  },
  {
    version: '6.24.1',
    id: 'Viktor',
    key: '112',
    name: 'Viktor',
    title: 'the Machine Herald',
    blurb:
      "Early in life, Viktor discovered his passion for science and invention, particularly in the field of mechanical automation. He attended Zaun's prestigious College of Techmaturgy and led the team that constructed Blitzcrank - a scientific breakthrough ...",
    info: {
      attack: 2,
      defense: 4,
      magic: 10,
      difficulty: 9,
    },
    image: {
      full: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt6e54b3de49b7bbf3/5db06015df78486c826dcd1e/RiotX_ChampionList_viktor.jpg?quality=90&width=250',
      sprite: 'champion3.png',
      group: 'champion',
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
    tags: ['Mage'],
    partype: 'MP',
    stats: {
      hp: 516.04,
      hpperlevel: 78.0,
      mp: 324.0,
      mpperlevel: 50.0,
      movespeed: 335.0,
      armor: 22.72,
      armorperlevel: 4.0,
      spellblock: 30.0,
      spellblockperlevel: 0.0,
      attackrange: 525.0,
      hpregen: 7.84,
      hpregenperlevel: 0.65,
      mpregen: 6.0,
      mpregenperlevel: 0.8,
      crit: 0.0,
      critperlevel: 0.0,
      attackdamage: 52.04,
      attackdamageperlevel: 3.0,
      attackspeedoffset: -0.05,
      attackspeedperlevel: 2.11,
    },
  },
  {
    version: '6.24.1',
    id: 'Heimerdinger',
    key: '74',
    name: 'Heimerdinger',
    title: 'the Revered Inventor',
    blurb:
      "From the Journal of Professor Cecil B. Heimerdinger<br><br>10.14<br><br>09:15<br><br>Current meteorological conditions in Bandle City seem optimal. Atmospheric pressure is ideal for today's experiments!<br><br>Running a fifth trial for my ...",
    info: {
      attack: 2,
      defense: 6,
      magic: 8,
      difficulty: 8,
    },
    image: {
      full: 'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/bltd30d85446d154070/5db05fc57d28b76cfe4397ef/RiotX_ChampionList_heimerdinger.jpg?quality=90&width=250',
      sprite: 'champion1.png',
      group: 'champion',
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
    tags: ['Mage', 'Support'],
    partype: 'MP',
    stats: {
      hp: 476.0,
      hpperlevel: 75.0,
      mp: 307.2,
      mpperlevel: 40.0,
      movespeed: 340.0,
      armor: 19.04,
      armorperlevel: 3.0,
      spellblock: 30.0,
      spellblockperlevel: 0.0,
      attackrange: 550.0,
      hpregen: 11.005,
      hpregenperlevel: 1.75,
      mpregen: 6.0,
      mpregenperlevel: 0.8,
      crit: 0.0,
      critperlevel: 0.0,
      attackdamage: 55.536,
      attackdamageperlevel: 2.7,
      attackspeedoffset: 0.0,
      attackspeedperlevel: 1.36,
    },
  },
];
